joe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('praxes/', include('praxes.urls')),
    path('mform/', include('mform.urls'))
]

mform/urls.py
from django.urls import path
from . import views

app_name = "mform"
urlpatterns = [
    path('', views.index, name='index'),
    path('form1/', views.form1, name='form1')
]

praxes/urls.py
from django.urls import path
from . import views

app_name = "praxes"
urlpatterns = [
    path('', views.index, name='index'),
    path('jquery/', views.jquery, name='jqery'),
    path('namen/', views.namen, name='namen')
]

mform/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

TITLE_CHOICES = (
    ('MR', 'Mr.'),
    ('MRS', 'Mrs.'),
    ('MS', 'Ms.'),
)

class Author(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=3, choices=TITLE_CHOICES)
    birth_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name

class Book(models.Model):
    name = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)

class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'title', 'birth_date']

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'authors']

praxes/models.py
from django.db import models

# Create your models here.

class Name(models.Model):
    vorname = models.CharField(max_length=35, blank=True)
    nachname = models.CharField(max_length=35, blank=True)
    anmerkung = models.TextField(blank=True)

    def __str__(self):
        return self.nachname

mform/views.py
from django.forms import modelformset_factory
from django.shortcuts import render
from mform.models import Author

# Create your views here.
def index(request):
    titel = "Das die FormApp"
    nachricht = "Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten."
    context = {'titel' : titel, 'nachricht' : nachricht}
    return render(request, 'index.html', context)

def form1(request):
    AuthorFormSet = modelformset_factory(Author, fields=('name', 'title'))
    if request.method == 'POST':
        formset = AuthorFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            #do something
    else:
        formset = AuthorFormSet()
    context = {'formset' : formset}
    return render(request, 'form1.html', context)

praxes/views.py
from django.shortcuts import render
from .models import Name

# Create your views here.


def index(request):
    titel = "Das ist der Titel"
    nachricht = "Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten."
    context = {'titel' : titel, 'nachricht' : nachricht}
    return render(request, 'index.html', context)

def jquery(request):
    titel = "Jquery Sandbox"
    nachricht = "Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten."
    context = {'titel' : titel, 'nachricht' : nachricht}
    return render(request, 'jquery.html', context)

def namen(request):
    titel = "Namensliste"
    namensliste = Name.objects.all()

    context = {'titel' : titel, 'namensliste' : namensliste}
    return render(request, 'namen.html', context)

mform/templates/base.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<!doctype html>
<html lang="de">
    <head>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
          
    </head>
<body>
        <nav class="nav">
                <a class="nav-link " href="{% url 'mform:index' %}">Home</a>
                <a class="nav-link" href="{% url 'mform:form1' %}">Form1</a>
                <!-- <a class="nav-link" href="{% url 'praxes:namen' %}">Namen</a> -->
        </nav>
              

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
   
  
</body>
</html>

mform/templates/form1.html
{% extends 'base.html' %}
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
<div>hi</div>
<form method="post">
    {% csrf_token %}
    {{ formset }}
</form>
{% endblock %}

mform/templates/index.html
{% extends 'base.html' %}
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
<h1>{{ titel }}</h1>
<p>

    {{ nachricht }}
</p>
{% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
<div>{% buttons submit='OK' reset="Cancel" %}{% endbuttons %}</div>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Holy guacamole!</strong> You should check in on some of those fields below.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endblock %}

praxes/templates/base.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<!doctype html>
<html lang="de">
    <head>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <script>
                $(document).ready(function(){
                    $("p").click(function(){
                        $(this).hide();
                    });
                });
                </script>
    </head>
<body>
        <nav class="nav">
                <a class="nav-link " href="{% url 'praxes:index' %}">Home</a>
                <a class="nav-link" href="{% url 'praxes:jqery' %}">JQuery</a>
                <a class="nav-link" href="{% url 'praxes:namen' %}">Namen</a>
        </nav>
              

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
        <p>hallo!</p>
    </div>
   
  
</body>
</html>

praxes/templates/jquery.html
{% extends 'base.html' %}
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
<h2>{{  titel }}</h2>

<script>
    $(document).ready(function(){
        $("p").click(function(){
            $(this).hide();
        });
    });
    </script>
       
    <p>If you click on me, I will disappear.</p>
    <p>Click me away!</p>
    <p>Click me too!</p>

{% endblock %}

praxes/templates/namen.html
{% extends 'base.html' %}
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
<h2>{{  titel }}</h2>
{% for name in namensliste  %}
<div id="accordianId" role="tablist" aria-multiselectable="true">
    <div class="card">
        <div class="card-header" role="tab" id="Header{}Id".format({{ name.vorname }})>
            <h5 class="mb-0">
                <a data-toggle="collapse" data-parent="#accordianId" href="#section1Content{}Id".format({{ name.vorname }}) aria-expanded="true" aria-controls="section1Content{}Id".format({{ name.vorname }})>
          {{ name.vorname }}
        </a>
            </h5>
        </div>
        <div id="section1Content{}Id".format({{ name.vorname }}) class="collapse in" role="tabpanel" aria-labelledby="section1Header{}Id".format({{ name.vorname }})>
            <div class="card-body">
                {{ name.vorname }} {{ name.nachname }}
                <p>{{ name.anmerkung }}</p>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}